using System.Collections.ObjectModel;
using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;
using CommunityToolkit.Mvvm.Messaging;
using PandaCubeTimer.Converters;
using PandaCubeTimer.Data.Repositories;
using PandaCubeTimer.Messages;
using PandaCubeTimer.Models;
using PandaCubeTimer.Stores;

namespace PandaCubeTimer.ViewModels;

public partial class SolvesViewModel : BaseViewModel
{
    private readonly PuzzleSolveRepository  _puzzleSolveRepository;
    private readonly ActiveSessionStore _activeSessionStore;
    
    
    
    [ObservableProperty]
    private ObservableCollection<PuzzleSolve> _puzzleSolves = new ObservableCollection<PuzzleSolve>();
    
    [ObservableProperty] 
    private bool _isRefreshing;

    [ObservableProperty]
    [NotifyPropertyChangedFor(nameof(IsOverlayVisible))]
    private PuzzleSolve? _selectedPuzzleSolve;

    [ObservableProperty]
    private bool? _isSelectedSolveCopiedSuccessfully;
    
    public bool IsOverlayVisible => SelectedPuzzleSolve != null;
    
    
    
    public SolvesViewModel(PuzzleSolveRepository puzzleSolveRepository,
                           ActiveSessionStore  activeSessionStore)
    {
        _puzzleSolveRepository = puzzleSolveRepository;
        _activeSessionStore = activeSessionStore;
        
        ConfigureMessageRecieving();
    }

    private void ConfigureMessageRecieving()
    {
        // reload solves for selected session:
        WeakReferenceMessenger.Default.Register<ActiveSessionChangedMessage>(this, (r, m) =>
        {
            OnActiveSessionChangedReceived(m.Value);
        });
    }

    
    
    private async void OnActiveSessionChangedReceived(Session messageValue)
    {
        try
        {
            await LoadSolvesAsync();
        }
        catch (Exception ex)
        {
            
        }
    }

    

    [RelayCommand]
    private async Task LoadSolvesAsync()
    {
        if(IsBusy)
            return;

        try
        {
            IsBusy = true;
            await LoadSolvesFromDbAsync(_activeSessionStore.CurrentSession.Id);
        }
        catch (Exception exception)
        {
            await Shell.Current.DisplayAlert("Error!", 
                $"Unable to load solves: {exception.Message}", "Ok");
        }
        finally
        {
            IsBusy = false;
            IsRefreshing = false;
        }
    }

    [RelayCommand]
    private void SelectPuzzleSolve(PuzzleSolve selectedSolve)
    {
        SelectedPuzzleSolve = selectedSolve;
    }

    [RelayCommand]
    private async Task DeleteSelectedPuzzleSolveAsync()
    {
        if(IsBusy)
            return;
        
        if (SelectedPuzzleSolve == null)
            return;

        try
        {
            await _puzzleSolveRepository.DeletePuzzleSolveAsync(SelectedPuzzleSolve);
            PuzzleSolves.Remove(SelectedPuzzleSolve);
            SelectedPuzzleSolve = null;
        }
        catch (Exception ex)
        {
            await Shell.Current.DisplayAlert("Error!",
                $"Unable to delete solve: {ex.Message}", "Ok");
        }
        finally
        {
            IsBusy = false;
        }
    }

    [RelayCommand]
    private async Task CopySolveToClipboardAsync()
    {
        if (IsBusy)
            return; 
        
        try
        {
            IsBusy = true;
            SolveToTimeConverter solveToTimeConverter = new SolveToTimeConverter();
            string formattedSolveTime = solveToTimeConverter.PuzzleSolveToTimeToDisplay(SelectedPuzzleSolve);

            string text = "Generated By PandaCubeTimer\n"
                          + formattedSolveTime
                          + ": "
                          + SelectedPuzzleSolve.Scramble;

            await Clipboard.Default.SetTextAsync(text);
            IsSelectedSolveCopiedSuccessfully = true;
        }
        catch (Exception)
        {
            IsSelectedSolveCopiedSuccessfully = false;
        }
        finally
        {
            IsBusy = false;
        }
    }

    [RelayCommand]
    private void ClosePuzzleSolve()
    {
        SelectedPuzzleSolve = null;
        IsSelectedSolveCopiedSuccessfully = null;
    }
    
    
    
    private async Task LoadSolvesFromDbAsync(Guid sessionId)
    {
        List<PuzzleSolve> solvesList = await _puzzleSolveRepository.GetSessionPuzzleSolvesAsync(sessionId);
        PuzzleSolves = new ObservableCollection<PuzzleSolve>(solvesList);
    }
}