using System.Collections.ObjectModel;
using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;
using PandaCubeTimer.Converters;
using PandaCubeTimer.Data;
using PandaCubeTimer.Models;

namespace PandaCubeTimer.ViewModels;

public partial class SolvesViewModel : BaseViewModel
{
    private readonly CubeTimerDb _database;
    
    [ObservableProperty]
    private ObservableCollection<PuzzleSolve> _puzzleSolves = new ObservableCollection<PuzzleSolve>();
    
    [ObservableProperty] 
    private bool _isRefreshing;

    [ObservableProperty]
    [NotifyPropertyChangedFor(nameof(IsOverlayVisible))]
    private PuzzleSolve? _selectedPuzzleSolve;

    [ObservableProperty]
    private bool? _isSelectedSolveCopiedSuccessfully;
    
    public bool IsOverlayVisible => SelectedPuzzleSolve != null;
    
    
    
    public SolvesViewModel(CubeTimerDb database)
    {
        _database = database;
    }

    

    [RelayCommand]
    private async Task LoadSolves()
    {
        if(IsBusy)
            return;

        try
        {
            IsBusy = true;
            await LoadSolvesFromDbAsync();
        }
        catch (Exception exception)
        {
            await Shell.Current.DisplayAlert("Error!", 
                $"Unable to load solves: {exception.Message}", "Ok");
        }
        finally
        {
            IsBusy = false;
            IsRefreshing = false;
        }
    }

    [RelayCommand]
    private void SelectPuzzleSolve(PuzzleSolve selectedSolve)
    {
        SelectedPuzzleSolve = selectedSolve;
    }

    [RelayCommand]
    private async Task DeleteSelectedPuzzleSolveAsync()
    {
        if(IsBusy)
            return;
        
        if (SelectedPuzzleSolve == null)
            return;

        try
        {
            await _database.Connection.DeleteAsync(SelectedPuzzleSolve);
            PuzzleSolves.Remove(SelectedPuzzleSolve);
            SelectedPuzzleSolve = null;
        }
        catch (Exception ex)
        {
            await Shell.Current.DisplayAlert("Error!",
                $"Unable to delete solve: {ex.Message}", "Ok");
        }
        finally
        {
            IsBusy = false;
        }
    }

    [RelayCommand]
    private async Task CopySolveToClipboardAsync()
    {
        if (IsBusy)
            return; 
        
        try
        {
            IsBusy = true;
            SolveToTimeConverter solveToTimeConverter = new SolveToTimeConverter();
            string formattedSolveTime = solveToTimeConverter.PuzzleSolveToTimeToDisplay(SelectedPuzzleSolve);

            string text = "Generated By PandaCubeTimer\n"
                          + formattedSolveTime
                          + ": "
                          + SelectedPuzzleSolve.Scramble;

            await Clipboard.Default.SetTextAsync(text);
            IsSelectedSolveCopiedSuccessfully = true;
        }
        catch (Exception)
        {
            IsSelectedSolveCopiedSuccessfully = false;
        }
        finally
        {
            IsBusy = false;
        }
    }

    [RelayCommand]
    private void ClosePuzzleSolve()
    {
        SelectedPuzzleSolve = null;
        IsSelectedSolveCopiedSuccessfully = null;
    }
    
    
    private async Task LoadSolvesFromDbAsync()
    {
        List<PuzzleSolve> solvesList = await _database.Connection.Table<PuzzleSolve>().OrderByDescending(s => s.DateTime).ToListAsync();
        PuzzleSolves = new ObservableCollection<PuzzleSolve>(solvesList);
    }
}